// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.Map;

/**
 * Schema of the Data property of an EventGridEvent for a Microsoft.Communication.ChatMessageReceived event.
 */
@Fluent
public final class AcsChatMessageReceivedEventData {

    /*
     * The body of the chat message
     */
    @JsonProperty(value = "messageBody")
    private String messageBody;

    /*
     * The chat message metadata
     */
    @JsonProperty(value = "metadata")
    private Map<String, String> metadata;

    /**
     * Creates an instance of AcsChatMessageReceivedEventData class.
     */
    public AcsChatMessageReceivedEventData() {
    }

    /**
     * Get the messageBody property: The body of the chat message.
     *
     * @return the messageBody value.
     */
    public String getMessageBody() {
        return this.messageBody;
    }

    /**
     * Set the messageBody property: The body of the chat message.
     *
     * @param messageBody the messageBody value to set.
     * @return the AcsChatMessageReceivedEventData object itself.
     */
    public AcsChatMessageReceivedEventData setMessageBody(String messageBody) {
        this.messageBody = messageBody;
        return this;
    }

    /**
     * Get the metadata property: The chat message metadata.
     *
     * @return the metadata value.
     */
    public Map<String, String> getMetadata() {
        return this.metadata;
    }

    /**
     * Set the metadata property: The chat message metadata.
     *
     * @param metadata the metadata value to set.
     * @return the AcsChatMessageReceivedEventData object itself.
     */
    public AcsChatMessageReceivedEventData setMetadata(Map<String, String> metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsChatMessageReceivedEventData setMessageId(String messageId) {
        super.setMessageId(messageId);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsChatMessageReceivedEventData
        setSenderCommunicationIdentifier(CommunicationIdentifierModel senderCommunicationIdentifier) {
        super.setSenderCommunicationIdentifier(senderCommunicationIdentifier);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsChatMessageReceivedEventData setSenderDisplayName(String senderDisplayName) {
        super.setSenderDisplayName(senderDisplayName);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsChatMessageReceivedEventData setComposeTime(OffsetDateTime composeTime) {
        super.setComposeTime(composeTime);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsChatMessageReceivedEventData setType(String type) {
        super.setType(type);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsChatMessageReceivedEventData setVersion(Long version) {
        super.setVersion(version);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsChatMessageReceivedEventData
        setRecipientCommunicationIdentifier(CommunicationIdentifierModel recipientCommunicationIdentifier) {
        super.setRecipientCommunicationIdentifier(recipientCommunicationIdentifier);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsChatMessageReceivedEventData setTransactionId(String transactionId) {
        super.setTransactionId(transactionId);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsChatMessageReceivedEventData setThreadId(String threadId) {
        super.setThreadId(threadId);
        return this;
    }

    /*
     * The communication identifier of the target user
     */
    @Generated
    @JsonProperty(value = "recipientCommunicationIdentifier")
    private CommunicationIdentifierModel recipientCommunicationIdentifier;

    /*
     * The transaction id will be used as co-relation vector
     */
    @Generated
    @JsonProperty(value = "transactionId")
    private String transactionId;

    /*
     * The chat thread id
     */
    @Generated
    @JsonProperty(value = "threadId")
    private String threadId;

    /*
     * The chat message id
     */
    @Generated
    @JsonProperty(value = "messageId")
    private String messageId;

    /*
     * The communication identifier of the sender
     */
    @Generated
    @JsonProperty(value = "senderCommunicationIdentifier")
    private CommunicationIdentifierModel senderCommunicationIdentifier;

    /*
     * The display name of the sender
     */
    @Generated
    @JsonProperty(value = "senderDisplayName")
    private String senderDisplayName;

    /*
     * The original compose time of the message
     */
    @Generated
    @JsonProperty(value = "composeTime")
    private OffsetDateTime composeTime;

    /*
     * The type of the message
     */
    @Generated
    @JsonProperty(value = "type")
    private String type;

    /*
     * The version of the message
     */
    @Generated
    @JsonProperty(value = "version")
    private Long version;

    /**
     * Get the recipientCommunicationIdentifier property: The communication identifier of the target user.
     *
     * @return the recipientCommunicationIdentifier value.
     */
    @Generated
    public CommunicationIdentifierModel getRecipientCommunicationIdentifier() {
        return this.recipientCommunicationIdentifier;
    }

    /**
     * Get the transactionId property: The transaction id will be used as co-relation vector.
     *
     * @return the transactionId value.
     */
    @Generated
    public String getTransactionId() {
        return this.transactionId;
    }

    /**
     * Get the threadId property: The chat thread id.
     *
     * @return the threadId value.
     */
    @Generated
    public String getThreadId() {
        return this.threadId;
    }

    /**
     * Get the messageId property: The chat message id.
     *
     * @return the messageId value.
     */
    @Generated
    public String getMessageId() {
        return this.messageId;
    }

    /**
     * Get the senderCommunicationIdentifier property: The communication identifier of the sender.
     *
     * @return the senderCommunicationIdentifier value.
     */
    @Generated
    public CommunicationIdentifierModel getSenderCommunicationIdentifier() {
        return this.senderCommunicationIdentifier;
    }

    /**
     * Get the senderDisplayName property: The display name of the sender.
     *
     * @return the senderDisplayName value.
     */
    @Generated
    public String getSenderDisplayName() {
        return this.senderDisplayName;
    }

    /**
     * Get the composeTime property: The original compose time of the message.
     *
     * @return the composeTime value.
     */
    @Generated
    public OffsetDateTime getComposeTime() {
        return this.composeTime;
    }

    /**
     * Get the type property: The type of the message.
     *
     * @return the type value.
     */
    @Generated
    public String getType() {
        return this.type;
    }

    /**
     * Get the version property: The version of the message.
     *
     * @return the version value.
     */
    @Generated
    public Long getVersion() {
        return this.version;
    }
}
