// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.Map;

/**
 * Schema of the Data property of an EventGridEvent for a Microsoft.Communication.ChatThreadPropertiesUpdatedPerUser
 * event.
 */
@Fluent
public final class AcsChatThreadPropertiesUpdatedPerUserEventData {

    /*
     * The communication identifier of the user who updated the thread properties
     */
    @JsonProperty(value = "editedByCommunicationIdentifier")
    private CommunicationIdentifierModel editedByCommunicationIdentifier;

    /*
     * The time at which the properties of the thread were updated
     */
    @JsonProperty(value = "editTime")
    private OffsetDateTime editTime;

    /*
     * The thread metadata
     */
    @JsonProperty(value = "metadata")
    private Map<String, String> metadata;

    /*
     * The updated thread properties
     */
    @JsonProperty(value = "properties")
    private Map<String, Object> properties;

    /**
     * Creates an instance of AcsChatThreadPropertiesUpdatedPerUserEventData class.
     */
    public AcsChatThreadPropertiesUpdatedPerUserEventData() {
    }

    /**
     * Get the editedByCommunicationIdentifier property: The communication identifier of the user who updated the thread
     * properties.
     *
     * @return the editedByCommunicationIdentifier value.
     */
    public CommunicationIdentifierModel getEditedByCommunicationIdentifier() {
        return this.editedByCommunicationIdentifier;
    }

    /**
     * Set the editedByCommunicationIdentifier property: The communication identifier of the user who updated the thread
     * properties.
     *
     * @param editedByCommunicationIdentifier the editedByCommunicationIdentifier value to set.
     * @return the AcsChatThreadPropertiesUpdatedPerUserEventData object itself.
     */
    public AcsChatThreadPropertiesUpdatedPerUserEventData
        setEditedByCommunicationIdentifier(CommunicationIdentifierModel editedByCommunicationIdentifier) {
        this.editedByCommunicationIdentifier = editedByCommunicationIdentifier;
        return this;
    }

    /**
     * Get the editTime property: The time at which the properties of the thread were updated.
     *
     * @return the editTime value.
     */
    public OffsetDateTime getEditTime() {
        return this.editTime;
    }

    /**
     * Set the editTime property: The time at which the properties of the thread were updated.
     *
     * @param editTime the editTime value to set.
     * @return the AcsChatThreadPropertiesUpdatedPerUserEventData object itself.
     */
    public AcsChatThreadPropertiesUpdatedPerUserEventData setEditTime(OffsetDateTime editTime) {
        this.editTime = editTime;
        return this;
    }

    /**
     * Get the metadata property: The thread metadata.
     *
     * @return the metadata value.
     */
    public Map<String, String> getMetadata() {
        return this.metadata;
    }

    /**
     * Set the metadata property: The thread metadata.
     *
     * @param metadata the metadata value to set.
     * @return the AcsChatThreadPropertiesUpdatedPerUserEventData object itself.
     */
    public AcsChatThreadPropertiesUpdatedPerUserEventData setMetadata(Map<String, String> metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Get the properties property: The updated thread properties.
     *
     * @return the properties value.
     */
    public Map<String, Object> getProperties() {
        return this.properties;
    }

    /**
     * Set the properties property: The updated thread properties.
     *
     * @param properties the properties value to set.
     * @return the AcsChatThreadPropertiesUpdatedPerUserEventData object itself.
     */
    public AcsChatThreadPropertiesUpdatedPerUserEventData setProperties(Map<String, Object> properties) {
        this.properties = properties;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsChatThreadPropertiesUpdatedPerUserEventData setCreateTime(OffsetDateTime createTime) {
        super.setCreateTime(createTime);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsChatThreadPropertiesUpdatedPerUserEventData setVersion(Long version) {
        super.setVersion(version);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsChatThreadPropertiesUpdatedPerUserEventData
        setRecipientCommunicationIdentifier(CommunicationIdentifierModel recipientCommunicationIdentifier) {
        super.setRecipientCommunicationIdentifier(recipientCommunicationIdentifier);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsChatThreadPropertiesUpdatedPerUserEventData setTransactionId(String transactionId) {
        super.setTransactionId(transactionId);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsChatThreadPropertiesUpdatedPerUserEventData setThreadId(String threadId) {
        super.setThreadId(threadId);
        return this;
    }

    /*
     * The communication identifier of the target user
     */
    @Generated
    @JsonProperty(value = "recipientCommunicationIdentifier")
    private CommunicationIdentifierModel recipientCommunicationIdentifier;

    /*
     * The transaction id will be used as co-relation vector
     */
    @Generated
    @JsonProperty(value = "transactionId")
    private String transactionId;

    /*
     * The chat thread id
     */
    @Generated
    @JsonProperty(value = "threadId")
    private String threadId;

    /*
     * The original creation time of the thread
     */
    @Generated
    @JsonProperty(value = "createTime")
    private OffsetDateTime createTime;

    /*
     * The version of the thread
     */
    @Generated
    @JsonProperty(value = "version")
    private Long version;

    /**
     * Get the recipientCommunicationIdentifier property: The communication identifier of the target user.
     *
     * @return the recipientCommunicationIdentifier value.
     */
    @Generated
    public CommunicationIdentifierModel getRecipientCommunicationIdentifier() {
        return this.recipientCommunicationIdentifier;
    }

    /**
     * Get the transactionId property: The transaction id will be used as co-relation vector.
     *
     * @return the transactionId value.
     */
    @Generated
    public String getTransactionId() {
        return this.transactionId;
    }

    /**
     * Get the threadId property: The chat thread id.
     *
     * @return the threadId value.
     */
    @Generated
    public String getThreadId() {
        return this.threadId;
    }

    /**
     * Get the createTime property: The original creation time of the thread.
     *
     * @return the createTime value.
     */
    @Generated
    public OffsetDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Get the version property: The version of the thread.
     *
     * @return the version value.
     */
    @Generated
    public Long getVersion() {
        return this.version;
    }
}
