// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

/**
 * Schema of the Data property of an EventGridEvent for a
 * Microsoft.Communication.RouterJobCancelled event.
 */
@Fluent
public final class AcsRouterJobCancelledEventData {

    /*
     * Router Job Note
     */
    @JsonProperty(value = "note")
    private String note;

    /*
     * Router Job Disposition Code
     */
    @JsonProperty(value = "dispositionCode")
    private String dispositionCode;

    /**
     * Creates an instance of AcsRouterJobCancelledEventData class.
     */
    public AcsRouterJobCancelledEventData() {
    }

    /**
     * Get the note property: Router Job Note.
     *
     * @return the note value.
     */
    public String getNote() {
        return this.note;
    }

    /**
     * Set the note property: Router Job Note.
     *
     * @param note the note value to set.
     * @return the AcsRouterJobCancelledEventData object itself.
     */
    public AcsRouterJobCancelledEventData setNote(String note) {
        this.note = note;
        return this;
    }

    /**
     * Get the dispositionCode property: Router Job Disposition Code.
     *
     * @return the dispositionCode value.
     */
    public String getDispositionCode() {
        return this.dispositionCode;
    }

    /**
     * Set the dispositionCode property: Router Job Disposition Code.
     *
     * @param dispositionCode the dispositionCode value to set.
     * @return the AcsRouterJobCancelledEventData object itself.
     */
    public AcsRouterJobCancelledEventData setDispositionCode(String dispositionCode) {
        this.dispositionCode = dispositionCode;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterJobCancelledEventData setQueueId(String queueId) {
        super.setQueueId(queueId);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterJobCancelledEventData setLabels(Map<String, String> labels) {
        super.setLabels(labels);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterJobCancelledEventData setTags(Map<String, String> tags) {
        super.setTags(tags);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterJobCancelledEventData setJobId(String jobId) {
        super.setJobId(jobId);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterJobCancelledEventData setChannelReference(String channelReference) {
        super.setChannelReference(channelReference);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterJobCancelledEventData setChannelId(String channelId) {
        super.setChannelId(channelId);
        return this;
    }

    /*
     * Router Event Job ID
     */
    @Generated
    @JsonProperty(value = "jobId")
    private String jobId;

    /*
     * Router Event Channel Reference
     */
    @Generated
    @JsonProperty(value = "channelReference")
    private String channelReference;

    /*
     * Router Event Channel ID
     */
    @Generated
    @JsonProperty(value = "channelId")
    private String channelId;

    /*
     * Router Job events Queue Id
     */
    @Generated
    @JsonProperty(value = "queueId")
    private String queueId;

    /*
     * Router Job events Labels
     */
    @Generated
    @JsonProperty(value = "labels")
    private Map<String, String> labels;

    /*
     * Router Jobs events Tags
     */
    @Generated
    @JsonProperty(value = "tags")
    private Map<String, String> tags;

    /**
     * Get the jobId property: Router Event Job ID.
     *
     * @return the jobId value.
     */
    @Generated
    public String getJobId() {
        return this.jobId;
    }

    /**
     * Get the channelReference property: Router Event Channel Reference.
     *
     * @return the channelReference value.
     */
    @Generated
    public String getChannelReference() {
        return this.channelReference;
    }

    /**
     * Get the channelId property: Router Event Channel ID.
     *
     * @return the channelId value.
     */
    @Generated
    public String getChannelId() {
        return this.channelId;
    }

    /**
     * Get the queueId property: Router Job events Queue Id.
     *
     * @return the queueId value.
     */
    @Generated
    public String getQueueId() {
        return this.queueId;
    }

    /**
     * Get the labels property: Router Job events Labels.
     *
     * @return the labels value.
     */
    @Generated
    public Map<String, String> getLabels() {
        return this.labels;
    }

    /**
     * Get the tags property: Router Jobs events Tags.
     *
     * @return the tags value.
     */
    @Generated
    public Map<String, String> getTags() {
        return this.tags;
    }
}
