// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Schema of the Data property of an EventGridEvent for a
 * Microsoft.Communication.RouterWorkerDeleted event.
 */
@Fluent
public final class AcsRouterWorkerDeletedEventData {

    /**
     * Creates an instance of AcsRouterWorkerDeletedEventData class.
     */
    public AcsRouterWorkerDeletedEventData() {
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterWorkerDeletedEventData setWorkerId(String workerId) {
        super.setWorkerId(workerId);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterWorkerDeletedEventData setJobId(String jobId) {
        super.setJobId(jobId);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterWorkerDeletedEventData setChannelReference(String channelReference) {
        super.setChannelReference(channelReference);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterWorkerDeletedEventData setChannelId(String channelId) {
        super.setChannelId(channelId);
        return this;
    }

    /*
     * Router Event Job ID
     */
    @Generated
    @JsonProperty(value = "jobId")
    private String jobId;

    /*
     * Router Event Channel Reference
     */
    @Generated
    @JsonProperty(value = "channelReference")
    private String channelReference;

    /*
     * Router Event Channel ID
     */
    @Generated
    @JsonProperty(value = "channelId")
    private String channelId;

    /*
     * Router Worker events Worker Id
     */
    @Generated
    @JsonProperty(value = "workerId")
    private String workerId;

    /**
     * Get the jobId property: Router Event Job ID.
     *
     * @return the jobId value.
     */
    @Generated
    public String getJobId() {
        return this.jobId;
    }

    /**
     * Get the channelReference property: Router Event Channel Reference.
     *
     * @return the channelReference value.
     */
    @Generated
    public String getChannelReference() {
        return this.channelReference;
    }

    /**
     * Get the channelId property: Router Event Channel ID.
     *
     * @return the channelId value.
     */
    @Generated
    public String getChannelId() {
        return this.channelId;
    }

    /**
     * Get the workerId property: Router Worker events Worker Id.
     *
     * @return the workerId value.
     */
    @Generated
    public String getWorkerId() {
        return this.workerId;
    }
}
