// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.azure.core.models.ResponseError;
import com.azure.messaging.eventgrid.implementation.models.AcsRouterCommunicationError;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Schema of the Data property of an EventGridEvent for a
 * Microsoft.Communication.RouterJobClassificationFailed event.
 */
@Fluent
public final class AcsRouterJobClassificationFailedEventData {

    /*
     * Router Job Classification Policy Id
     */
    @JsonProperty(value = "classificationPolicyId")
    private String classificationPolicyId;

    /*
     * Router Job Classification Failed Errors
     */
    @JsonProperty(value = "errors")
    private List<AcsRouterCommunicationError> errors;

    /**
     * Creates an instance of AcsRouterJobClassificationFailedEventData class.
     */
    public AcsRouterJobClassificationFailedEventData() {
    }

    /**
     * Get the classificationPolicyId property: Router Job Classification Policy Id.
     *
     * @return the classificationPolicyId value.
     */
    public String getClassificationPolicyId() {
        return this.classificationPolicyId;
    }

    /**
     * Set the classificationPolicyId property: Router Job Classification Policy Id.
     *
     * @param classificationPolicyId the classificationPolicyId value to set.
     * @return the AcsRouterJobClassificationFailedEventData object itself.
     */
    public AcsRouterJobClassificationFailedEventData setClassificationPolicyId(String classificationPolicyId) {
        this.classificationPolicyId = classificationPolicyId;
        return this;
    }

    /**
     * Get the errors property: Router Job Classification Failed Errors.
     *
     * @return the errors value.
     */
    public List<ResponseError> getErrors() {
        return this.errors.stream().map(e -> new ResponseError(e.getCode(), e.getMessage()))
            .collect(Collectors.toList());
    }

    /**
     * Set the errors property: Router Job Classification Failed Errors.
     *
     * @param errors the errors value to set.
     * @return the AcsRouterJobClassificationFailedEventData object itself.
     */
    public AcsRouterJobClassificationFailedEventData setErrors(List<ResponseError> errors) {
        this.errors = errors.stream()
            .map(e -> new AcsRouterCommunicationError().setCode(e.getCode()).setMessage(e.getMessage()))
            .collect(Collectors.toList());
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterJobClassificationFailedEventData setQueueId(String queueId) {
        super.setQueueId(queueId);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterJobClassificationFailedEventData setLabels(Map<String, String> labels) {
        super.setLabels(labels);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterJobClassificationFailedEventData setTags(Map<String, String> tags) {
        super.setTags(tags);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterJobClassificationFailedEventData setJobId(String jobId) {
        super.setJobId(jobId);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterJobClassificationFailedEventData setChannelReference(String channelReference) {
        super.setChannelReference(channelReference);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterJobClassificationFailedEventData setChannelId(String channelId) {
        super.setChannelId(channelId);
        return this;
    }

    /*
     * Router Event Job ID
     */
    @Generated
    @JsonProperty(value = "jobId")
    private String jobId;

    /*
     * Router Event Channel Reference
     */
    @Generated
    @JsonProperty(value = "channelReference")
    private String channelReference;

    /*
     * Router Event Channel ID
     */
    @Generated
    @JsonProperty(value = "channelId")
    private String channelId;

    /*
     * Router Job events Queue Id
     */
    @Generated
    @JsonProperty(value = "queueId")
    private String queueId;

    /*
     * Router Job events Labels
     */
    @Generated
    @JsonProperty(value = "labels")
    private Map<String, String> labels;

    /*
     * Router Jobs events Tags
     */
    @Generated
    @JsonProperty(value = "tags")
    private Map<String, String> tags;

    /**
     * Get the jobId property: Router Event Job ID.
     *
     * @return the jobId value.
     */
    @Generated
    public String getJobId() {
        return this.jobId;
    }

    /**
     * Get the channelReference property: Router Event Channel Reference.
     *
     * @return the channelReference value.
     */
    @Generated
    public String getChannelReference() {
        return this.channelReference;
    }

    /**
     * Get the channelId property: Router Event Channel ID.
     *
     * @return the channelId value.
     */
    @Generated
    public String getChannelId() {
        return this.channelId;
    }

    /**
     * Get the queueId property: Router Job events Queue Id.
     *
     * @return the queueId value.
     */
    @Generated
    public String getQueueId() {
        return this.queueId;
    }

    /**
     * Get the labels property: Router Job events Labels.
     *
     * @return the labels value.
     */
    @Generated
    public Map<String, String> getLabels() {
        return this.labels;
    }

    /**
     * Get the tags property: Router Jobs events Tags.
     *
     * @return the tags value.
     */
    @Generated
    public Map<String, String> getTags() {
        return this.tags;
    }
}
