// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;

/**
 * Schema of the Data property of an EventGridEvent for a
 * Microsoft.Communication.RouterJobSchedulingFailed event.
 */
@Fluent
public final class AcsRouterJobSchedulingFailedEventData {

    /*
     * Router Job Priority
     */
    @JsonProperty(value = "priority")
    private Integer priority;

    /*
     * Router Job Scheduling Failed Attached Worker Selector Expired
     */
    @JsonProperty(value = "expiredAttachedWorkerSelectors")
    private List<AcsRouterWorkerSelector> expiredAttachedWorkerSelectors;

    /*
     * Router Job Scheduling Failed Requested Worker Selector Expired
     */
    @JsonProperty(value = "expiredRequestedWorkerSelectors")
    private List<AcsRouterWorkerSelector> expiredRequestedWorkerSelectors;

    /*
     * Router Job Scheduling Failed Scheduled Time in UTC
     */
    @JsonProperty(value = "scheduledOn")
    private OffsetDateTime scheduledOn;

    /*
     * Router Job Scheduling Failed Reason
     */
    @JsonProperty(value = "failureReason")
    private String failureReason;

    /**
     * Creates an instance of AcsRouterJobSchedulingFailedEventData class.
     */
    public AcsRouterJobSchedulingFailedEventData() {
    }

    /**
     * Get the priority property: Router Job Priority.
     *
     * @return the priority value.
     */
    public Integer getPriority() {
        return this.priority;
    }

    /**
     * Set the priority property: Router Job Priority.
     *
     * @param priority the priority value to set.
     * @return the AcsRouterJobSchedulingFailedEventData object itself.
     */
    public AcsRouterJobSchedulingFailedEventData setPriority(Integer priority) {
        this.priority = priority;
        return this;
    }

    /**
     * Get the expiredAttachedWorkerSelectors property: Router Job Scheduling Failed Attached Worker Selector Expired.
     *
     * @return the expiredAttachedWorkerSelectors value.
     */
    public List<AcsRouterWorkerSelector> getExpiredAttachedWorkerSelectors() {
        return this.expiredAttachedWorkerSelectors;
    }

    /**
     * Set the expiredAttachedWorkerSelectors property: Router Job Scheduling Failed Attached Worker Selector Expired.
     *
     * @param expiredAttachedWorkerSelectors the expiredAttachedWorkerSelectors value to set.
     * @return the AcsRouterJobSchedulingFailedEventData object itself.
     */
    public AcsRouterJobSchedulingFailedEventData
        setExpiredAttachedWorkerSelectors(List<AcsRouterWorkerSelector> expiredAttachedWorkerSelectors) {
        this.expiredAttachedWorkerSelectors = expiredAttachedWorkerSelectors;
        return this;
    }

    /**
     * Get the expiredRequestedWorkerSelectors property: Router Job Scheduling Failed Requested Worker Selector Expired.
     *
     * @return the expiredRequestedWorkerSelectors value.
     */
    public List<AcsRouterWorkerSelector> getExpiredRequestedWorkerSelectors() {
        return this.expiredRequestedWorkerSelectors;
    }

    /**
     * Set the expiredRequestedWorkerSelectors property: Router Job Scheduling Failed Requested Worker Selector Expired.
     *
     * @param expiredRequestedWorkerSelectors the expiredRequestedWorkerSelectors value to set.
     * @return the AcsRouterJobSchedulingFailedEventData object itself.
     */
    public AcsRouterJobSchedulingFailedEventData
        setExpiredRequestedWorkerSelectors(List<AcsRouterWorkerSelector> expiredRequestedWorkerSelectors) {
        this.expiredRequestedWorkerSelectors = expiredRequestedWorkerSelectors;
        return this;
    }

    /**
     * Get the scheduledOn property: Router Job Scheduling Failed Scheduled Time in UTC.
     *
     * @return the scheduledOn value.
     */
    public OffsetDateTime getScheduledOn() {
        return this.scheduledOn;
    }

    /**
     * Set the scheduledOn property: Router Job Scheduling Failed Scheduled Time in UTC.
     *
     * @param scheduledOn the scheduledOn value to set.
     * @return the AcsRouterJobSchedulingFailedEventData object itself.
     */
    public AcsRouterJobSchedulingFailedEventData setScheduledOn(OffsetDateTime scheduledOn) {
        this.scheduledOn = scheduledOn;
        return this;
    }

    /**
     * Get the failureReason property: Router Job Scheduling Failed Reason.
     *
     * @return the failureReason value.
     */
    public String getFailureReason() {
        return this.failureReason;
    }

    /**
     * Set the failureReason property: Router Job Scheduling Failed Reason.
     *
     * @param failureReason the failureReason value to set.
     * @return the AcsRouterJobSchedulingFailedEventData object itself.
     */
    public AcsRouterJobSchedulingFailedEventData setFailureReason(String failureReason) {
        this.failureReason = failureReason;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterJobSchedulingFailedEventData setQueueId(String queueId) {
        super.setQueueId(queueId);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterJobSchedulingFailedEventData setLabels(Map<String, String> labels) {
        super.setLabels(labels);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterJobSchedulingFailedEventData setTags(Map<String, String> tags) {
        super.setTags(tags);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterJobSchedulingFailedEventData setJobId(String jobId) {
        super.setJobId(jobId);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterJobSchedulingFailedEventData setChannelReference(String channelReference) {
        super.setChannelReference(channelReference);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcsRouterJobSchedulingFailedEventData setChannelId(String channelId) {
        super.setChannelId(channelId);
        return this;
    }

    /*
     * Router Event Job ID
     */
    @Generated
    @JsonProperty(value = "jobId")
    private String jobId;

    /*
     * Router Event Channel Reference
     */
    @Generated
    @JsonProperty(value = "channelReference")
    private String channelReference;

    /*
     * Router Event Channel ID
     */
    @Generated
    @JsonProperty(value = "channelId")
    private String channelId;

    /*
     * Router Job events Queue Id
     */
    @Generated
    @JsonProperty(value = "queueId")
    private String queueId;

    /*
     * Router Job events Labels
     */
    @Generated
    @JsonProperty(value = "labels")
    private Map<String, String> labels;

    /*
     * Router Jobs events Tags
     */
    @Generated
    @JsonProperty(value = "tags")
    private Map<String, String> tags;

    /**
     * Get the jobId property: Router Event Job ID.
     *
     * @return the jobId value.
     */
    @Generated
    public String getJobId() {
        return this.jobId;
    }

    /**
     * Get the channelReference property: Router Event Channel Reference.
     *
     * @return the channelReference value.
     */
    @Generated
    public String getChannelReference() {
        return this.channelReference;
    }

    /**
     * Get the channelId property: Router Event Channel ID.
     *
     * @return the channelId value.
     */
    @Generated
    public String getChannelId() {
        return this.channelId;
    }

    /**
     * Get the queueId property: Router Job events Queue Id.
     *
     * @return the queueId value.
     */
    @Generated
    public String getQueueId() {
        return this.queueId;
    }

    /**
     * Get the labels property: Router Job events Labels.
     *
     * @return the labels value.
     */
    @Generated
    public Map<String, String> getLabels() {
        return this.labels;
    }

    /**
     * Get the tags property: Router Jobs events Tags.
     *
     * @return the tags value.
     */
    @Generated
    public Map<String, String> getTags() {
        return this.tags;
    }
}
