// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Schema of the Data property of an EventGridEvent for a Microsoft.AppConfiguration.SnapshotCreated event.
 */
@Immutable
public final class AppConfigurationSnapshotCreatedEventData {

    /**
     * Creates an instance of AppConfigurationSnapshotCreatedEventData class.
     */
    public AppConfigurationSnapshotCreatedEventData() {
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppConfigurationSnapshotCreatedEventData setName(String name) {
        super.setName(name);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppConfigurationSnapshotCreatedEventData setEtag(String etag) {
        super.setEtag(etag);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppConfigurationSnapshotCreatedEventData setSyncToken(String syncToken) {
        super.setSyncToken(syncToken);
        return this;
    }

    /*
     * The name of the snapshot.
     */
    @Generated
    @JsonProperty(value = "name")
    private String name;

    /*
     * The etag representing the new state of the snapshot.
     */
    @Generated
    @JsonProperty(value = "etag")
    private String etag;

    /*
     * The sync token representing the server state after the event.
     */
    @Generated
    @JsonProperty(value = "syncToken")
    private String syncToken;

    /**
     * Get the name property: The name of the snapshot.
     *
     * @return the name value.
     */
    @Generated
    public String getName() {
        return this.name;
    }

    /**
     * Get the etag property: The etag representing the new state of the snapshot.
     *
     * @return the etag value.
     */
    @Generated
    public String getEtag() {
        return this.etag;
    }

    /**
     * Get the syncToken property: The sync token representing the server state after the event.
     *
     * @return the syncToken value.
     */
    @Generated
    public String getSyncToken() {
        return this.syncToken;
    }
}
