// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The registry node that generated the event. Put differently, while the actor initiates the event, the source
 * generates it.
 */
@Fluent
public final class ContainerRegistryEventSource {

    /*
     * The IP or hostname and the port of the registry node that generated the event. Generally, this will be resolved
     * by os.Hostname() along with the running port.
     */
    @JsonProperty(value = "addr")
    private String addr;

    /*
     * The running instance of an application. Changes after each restart.
     */
    @JsonProperty(value = "instanceID")
    private String instanceID;

    /**
     * Creates an instance of ContainerRegistryEventSource class.
     */
    public ContainerRegistryEventSource() {
    }

    /**
     * Get the addr property: The IP or hostname and the port of the registry node that generated the event. Generally,
     * this will be resolved by os.Hostname() along with the running port.
     *
     * @return the addr value.
     */
    public String getAddr() {
        return this.addr;
    }

    /**
     * Set the addr property: The IP or hostname and the port of the registry node that generated the event. Generally,
     * this will be resolved by os.Hostname() along with the running port.
     *
     * @param addr the addr value to set.
     * @return the ContainerRegistryEventSource object itself.
     */
    public ContainerRegistryEventSource setAddr(String addr) {
        this.addr = addr;
        return this;
    }

    /**
     * Get the instanceID property: The running instance of an application. Changes after each restart.
     *
     * @return the instanceID value.
     */
    public String getInstanceID() {
        return this.instanceID;
    }

    /**
     * Set the instanceID property: The running instance of an application. Changes after each restart.
     *
     * @param instanceID the instanceID value to set.
     * @return the ContainerRegistryEventSource object itself.
     */
    public ContainerRegistryEventSource setInstanceID(String instanceID) {
        this.instanceID = instanceID;
        return this;
    }

    /*
     * The running instance of an application. Changes after each restart.
     */
    @Generated
    @JsonProperty(value = "instanceID")
    private String instanceId;

    /**
     * Get the instanceId property: The running instance of an application. Changes after each restart.
     *
     * @return the instanceId value.
     */
    @Generated
    public String getInstanceId() {
        return this.instanceId;
    }

    /**
     * Set the instanceId property: The running instance of an application. Changes after each restart.
     *
     * @param instanceId the instanceId value to set.
     * @return the ContainerRegistryEventSource object itself.
     */
    @Generated
    public ContainerRegistryEventSource setInstanceId(String instanceId) {
        this.instanceId = instanceId;
        return this;
    }
}
