// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Schema of the Data property of an EventGridEvent for a Microsoft.ContainerService.NodePoolRollingSucceeded event.
 */
@Fluent
public final class ContainerServiceNodePoolRollingSucceededEventData {

    /**
     * Creates an instance of ContainerServiceNodePoolRollingSucceededEventData class.
     */
    public ContainerServiceNodePoolRollingSucceededEventData() {
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContainerServiceNodePoolRollingSucceededEventData setNodePoolName(String nodePoolName) {
        super.setNodePoolName(nodePoolName);
        return this;
    }

    /*
     * The name of the node pool in the ManagedCluster resource
     */
    @Generated
    @JsonProperty(value = "nodePoolName")
    private String nodePoolName;

    /**
     * Get the nodePoolName property: The name of the node pool in the ManagedCluster resource.
     *
     * @return the nodePoolName value.
     */
    @Generated
    public String getNodePoolName() {
        return this.nodePoolName;
    }
}
