// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/**
 * Schema of the Data property of an EventGridEvent for a Microsoft.ContainerRegistry.ChartDeleted event.
 */
@Fluent
public final class ContainerRegistryChartDeletedEventData {

    /**
     * Creates an instance of ContainerRegistryChartDeletedEventData class.
     */
    public ContainerRegistryChartDeletedEventData() {
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContainerRegistryChartDeletedEventData setId(String id) {
        super.setId(id);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContainerRegistryChartDeletedEventData setTimestamp(OffsetDateTime timestamp) {
        super.setTimestamp(timestamp);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContainerRegistryChartDeletedEventData setAction(String action) {
        super.setAction(action);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContainerRegistryChartDeletedEventData setLocation(String location) {
        super.setLocation(location);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContainerRegistryChartDeletedEventData setTarget(ContainerRegistryArtifactEventTarget target) {
        super.setTarget(target);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContainerRegistryChartDeletedEventData
        setConnectedRegistry(ContainerRegistryEventConnectedRegistry connectedRegistry) {
        super.setConnectedRegistry(connectedRegistry);
        return this;
    }

    /*
     * The event ID.
     */
    @Generated
    @JsonProperty(value = "id")
    private String id;

    /*
     * The time at which the event occurred.
     */
    @Generated
    @JsonProperty(value = "timestamp")
    private OffsetDateTime timestamp;

    /*
     * The action that encompasses the provided event.
     */
    @Generated
    @JsonProperty(value = "action")
    private String action;

    /*
     * The location of the event.
     */
    @Generated
    @JsonProperty(value = "location")
    private String location;

    /*
     * The target of the event.
     */
    @Generated
    @JsonProperty(value = "target")
    private ContainerRegistryArtifactEventTarget target;

    /*
     * The connected registry information if the event is generated by a connected registry.
     */
    @Generated
    @JsonProperty(value = "connectedRegistry")
    private ContainerRegistryEventConnectedRegistry connectedRegistry;

    /**
     * Get the id property: The event ID.
     *
     * @return the id value.
     */
    @Generated
    public String getId() {
        return this.id;
    }

    /**
     * Get the timestamp property: The time at which the event occurred.
     *
     * @return the timestamp value.
     */
    @Generated
    public OffsetDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Get the action property: The action that encompasses the provided event.
     *
     * @return the action value.
     */
    @Generated
    public String getAction() {
        return this.action;
    }

    /**
     * Get the location property: The location of the event.
     *
     * @return the location value.
     */
    @Generated
    public String getLocation() {
        return this.location;
    }

    /**
     * Get the target property: The target of the event.
     *
     * @return the target value.
     */
    @Generated
    public ContainerRegistryArtifactEventTarget getTarget() {
        return this.target;
    }

    /**
     * Get the connectedRegistry property: The connected registry information if the event is generated by a connected
     * registry.
     *
     * @return the connectedRegistry value.
     */
    @Generated
    public ContainerRegistryEventConnectedRegistry getConnectedRegistry() {
        return this.connectedRegistry;
    }
}
