// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Schema of the Data property of an EventGridEvent for a Microsoft.ContainerService.ClusterSupportEnding event.
 */
@Fluent
public final class ContainerServiceClusterSupportEndingEventData {

    /**
     * Creates an instance of ContainerServiceClusterSupportEndingEventData class.
     */
    public ContainerServiceClusterSupportEndingEventData() {
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContainerServiceClusterSupportEndingEventData setKubernetesVersion(String kubernetesVersion) {
        super.setKubernetesVersion(kubernetesVersion);
        return this;
    }

    /*
     * The Kubernetes version of the ManagedCluster resource
     */
    @Generated
    @JsonProperty(value = "kubernetesVersion")
    private String kubernetesVersion;

    /**
     * Get the kubernetesVersion property: The Kubernetes version of the ManagedCluster resource.
     *
     * @return the kubernetesVersion value.
     */
    @Generated
    public String getKubernetesVersion() {
        return this.kubernetesVersion;
    }
}
