// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Event data for Microsoft.EventGrid.MQTTClientSessionConnected event.
 */
@Fluent
public final class EventGridMqttClientSessionConnectedEventData {

    /*
     * Unique identifier for the MQTT client's session. This case-sensitive string can be up to 128 characters long,
     * and supports UTF-8 characters.
     */
    @JsonProperty(value = "clientSessionName")
    private String clientSessionName;

    /*
     * A number that helps indicate order of MQTT client session connected or disconnected events. Latest event will
     * have a sequence number that is higher than the previous event.
     */
    @JsonProperty(value = "sequenceNumber")
    private Long sequenceNumber;

    /**
     * Creates an instance of EventGridMqttClientSessionConnectedEventData class.
     */
    public EventGridMqttClientSessionConnectedEventData() {
    }

    /**
     * Get the clientSessionName property: Unique identifier for the MQTT client's session. This case-sensitive string
     * can be up to 128 characters long, and supports UTF-8 characters.
     *
     * @return the clientSessionName value.
     */
    public String getClientSessionName() {
        return this.clientSessionName;
    }

    /**
     * Set the clientSessionName property: Unique identifier for the MQTT client's session. This case-sensitive string
     * can be up to 128 characters long, and supports UTF-8 characters.
     *
     * @param clientSessionName the clientSessionName value to set.
     * @return the EventGridMqttClientSessionConnectedEventData object itself.
     */
    public EventGridMqttClientSessionConnectedEventData setClientSessionName(String clientSessionName) {
        this.clientSessionName = clientSessionName;
        return this;
    }

    /**
     * Get the sequenceNumber property: A number that helps indicate order of MQTT client session connected or
     * disconnected events. Latest event will have a sequence number that is higher than the previous event.
     *
     * @return the sequenceNumber value.
     */
    public Long getSequenceNumber() {
        return this.sequenceNumber;
    }

    /**
     * Set the sequenceNumber property: A number that helps indicate order of MQTT client session connected or
     * disconnected events. Latest event will have a sequence number that is higher than the previous event.
     *
     * @param sequenceNumber the sequenceNumber value to set.
     * @return the EventGridMqttClientSessionConnectedEventData object itself.
     */
    public EventGridMqttClientSessionConnectedEventData setSequenceNumber(Long sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventGridMqttClientSessionConnectedEventData setClientAuthenticationName(String clientAuthenticationName) {
        super.setClientAuthenticationName(clientAuthenticationName);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventGridMqttClientSessionConnectedEventData setClientName(String clientName) {
        super.setClientName(clientName);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventGridMqttClientSessionConnectedEventData setNamespaceName(String namespaceName) {
        super.setNamespaceName(namespaceName);
        return this;
    }

    /*
     * Unique identifier for the MQTT client that the client presents to the service
     * for authentication. This case-sensitive string can be up to 128 characters
     * long, and supports UTF-8 characters.
     */
    @Generated
    @JsonProperty(value = "clientAuthenticationName")
    private String clientAuthenticationName;

    /*
     * Name of the client resource in the Event Grid namespace.
     */
    @Generated
    @JsonProperty(value = "clientName")
    private String clientName;

    /*
     * Name of the Event Grid namespace where the MQTT client was created or updated.
     */
    @Generated
    @JsonProperty(value = "namespaceName")
    private String namespaceName;

    /**
     * Get the clientAuthenticationName property: Unique identifier for the MQTT client that the client presents to the
     * service
     * for authentication. This case-sensitive string can be up to 128 characters
     * long, and supports UTF-8 characters.
     *
     * @return the clientAuthenticationName value.
     */
    @Generated
    public String getClientAuthenticationName() {
        return this.clientAuthenticationName;
    }

    /**
     * Get the clientName property: Name of the client resource in the Event Grid namespace.
     *
     * @return the clientName value.
     */
    @Generated
    public String getClientName() {
        return this.clientName;
    }

    /**
     * Get the namespaceName property: Name of the Event Grid namespace where the MQTT client was created or updated.
     *
     * @return the namespaceName value.
     */
    @Generated
    public String getNamespaceName() {
        return this.namespaceName;
    }
}
