// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Schema of the Data property of an EventGridEvent for a Microsoft.HealthcareApis.FhirResourceDeleted event.
 */
@Fluent
public final class HealthcareFhirResourceDeletedEventData {

    /*
     * Type of HL7 FHIR resource.
     */
    @JsonProperty(value = "resourceType")
    private HealthcareFhirResourceType fhirResourceType;

    /*
     * Domain name of FHIR account for this resource.
     */
    @JsonProperty(value = "resourceFhirAccount")
    private String fhirServiceHostName;

    /*
     * Id of HL7 FHIR resource.
     */
    @JsonProperty(value = "resourceFhirId")
    private String fhirResourceId;

    /*
     * VersionId of HL7 FHIR resource. It changes when the resource is created, updated, or deleted(soft-deletion).
     */
    @JsonProperty(value = "resourceVersionId")
    private Long fhirResourceVersionId;

    /**
     * Creates an instance of HealthcareFhirResourceDeletedEventData class.
     */
    public HealthcareFhirResourceDeletedEventData() {
    }

    /**
     * Get the fhirResourceType property: Type of HL7 FHIR resource.
     *
     * @return the fhirResourceType value.
     */
    public HealthcareFhirResourceType getFhirResourceType() {
        return this.fhirResourceType;
    }

    /**
     * Set the fhirResourceType property: Type of HL7 FHIR resource.
     *
     * @param fhirResourceType the fhirResourceType value to set.
     * @return the HealthcareFhirResourceDeletedEventData object itself.
     */
    public HealthcareFhirResourceDeletedEventData setFhirResourceType(HealthcareFhirResourceType fhirResourceType) {
        this.fhirResourceType = fhirResourceType;
        return this;
    }

    /**
     * Get the fhirServiceHostName property: Domain name of FHIR account for this resource.
     *
     * @return the fhirServiceHostName value.
     */
    public String getFhirServiceHostName() {
        return this.fhirServiceHostName;
    }

    /**
     * Set the fhirServiceHostName property: Domain name of FHIR account for this resource.
     *
     * @param fhirServiceHostName the fhirServiceHostName value to set.
     * @return the HealthcareFhirResourceDeletedEventData object itself.
     */
    public HealthcareFhirResourceDeletedEventData setFhirServiceHostName(String fhirServiceHostName) {
        this.fhirServiceHostName = fhirServiceHostName;
        return this;
    }

    /**
     * Get the fhirResourceId property: Id of HL7 FHIR resource.
     *
     * @return the fhirResourceId value.
     */
    public String getFhirResourceId() {
        return this.fhirResourceId;
    }

    /**
     * Set the fhirResourceId property: Id of HL7 FHIR resource.
     *
     * @param fhirResourceId the fhirResourceId value to set.
     * @return the HealthcareFhirResourceDeletedEventData object itself.
     */
    public HealthcareFhirResourceDeletedEventData setFhirResourceId(String fhirResourceId) {
        this.fhirResourceId = fhirResourceId;
        return this;
    }

    /**
     * Get the fhirResourceVersionId property: VersionId of HL7 FHIR resource. It changes when the resource is created,
     * updated, or deleted(soft-deletion).
     *
     * @return the fhirResourceVersionId value.
     */
    public Long getFhirResourceVersionId() {
        return this.fhirResourceVersionId;
    }

    /**
     * Set the fhirResourceVersionId property: VersionId of HL7 FHIR resource. It changes when the resource is created,
     * updated, or deleted(soft-deletion).
     *
     * @param fhirResourceVersionId the fhirResourceVersionId value to set.
     * @return the HealthcareFhirResourceDeletedEventData object itself.
     */
    public HealthcareFhirResourceDeletedEventData setFhirResourceVersionId(Long fhirResourceVersionId) {
        this.fhirResourceVersionId = fhirResourceVersionId;
        return this;
    }

    /*
     * Domain name of FHIR account for this resource.
     */
    @Generated
    @JsonProperty(value = "resourceFhirAccount")
    private String resourceFhirAccount;

    /*
     * Id of HL7 FHIR resource.
     */
    @Generated
    @JsonProperty(value = "resourceFhirId")
    private String resourceFhirId;

    /*
     * VersionId of HL7 FHIR resource. It changes when the resource is created, updated, or deleted(soft-deletion).
     */
    @Generated
    @JsonProperty(value = "resourceVersionId")
    private Long resourceVersionId;

    /*
     * Type of HL7 FHIR resource.
     */
    @Generated
    @JsonProperty(value = "resourceType")
    private HealthcareFhirResourceType resourceType;

    /**
     * Get the resourceFhirAccount property: Domain name of FHIR account for this resource.
     *
     * @return the resourceFhirAccount value.
     */
    @Generated
    public String getResourceFhirAccount() {
        return this.resourceFhirAccount;
    }

    /**
     * Set the resourceFhirAccount property: Domain name of FHIR account for this resource.
     *
     * @param resourceFhirAccount the resourceFhirAccount value to set.
     * @return the HealthcareFhirResourceDeletedEventData object itself.
     */
    @Generated
    public HealthcareFhirResourceDeletedEventData setResourceFhirAccount(String resourceFhirAccount) {
        this.resourceFhirAccount = resourceFhirAccount;
        return this;
    }

    /**
     * Get the resourceFhirId property: Id of HL7 FHIR resource.
     *
     * @return the resourceFhirId value.
     */
    @Generated
    public String getResourceFhirId() {
        return this.resourceFhirId;
    }

    /**
     * Set the resourceFhirId property: Id of HL7 FHIR resource.
     *
     * @param resourceFhirId the resourceFhirId value to set.
     * @return the HealthcareFhirResourceDeletedEventData object itself.
     */
    @Generated
    public HealthcareFhirResourceDeletedEventData setResourceFhirId(String resourceFhirId) {
        this.resourceFhirId = resourceFhirId;
        return this;
    }

    /**
     * Get the resourceVersionId property: VersionId of HL7 FHIR resource. It changes when the resource is created,
     * updated, or deleted(soft-deletion).
     *
     * @return the resourceVersionId value.
     */
    @Generated
    public Long getResourceVersionId() {
        return this.resourceVersionId;
    }

    /**
     * Set the resourceVersionId property: VersionId of HL7 FHIR resource. It changes when the resource is created,
     * updated, or deleted(soft-deletion).
     *
     * @param resourceVersionId the resourceVersionId value to set.
     * @return the HealthcareFhirResourceDeletedEventData object itself.
     */
    @Generated
    public HealthcareFhirResourceDeletedEventData setResourceVersionId(Long resourceVersionId) {
        this.resourceVersionId = resourceVersionId;
        return this;
    }

    /**
     * Get the resourceType property: Type of HL7 FHIR resource.
     *
     * @return the resourceType value.
     */
    @Generated
    public HealthcareFhirResourceType getResourceType() {
        return this.resourceType;
    }

    /**
     * Set the resourceType property: Type of HL7 FHIR resource.
     *
     * @param resourceType the resourceType value to set.
     * @return the HealthcareFhirResourceDeletedEventData object itself.
     */
    @Generated
    public HealthcareFhirResourceDeletedEventData setResourceType(HealthcareFhirResourceType resourceType) {
        this.resourceType = resourceType;
        return this;
    }
}
