// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

/**
 * Event data for Microsoft.Devices.DeviceTelemetry event.
 */
@Fluent
public final class IotHubDeviceTelemetryEventData {

    /**
     * Creates an instance of IotHubDeviceTelemetryEventData class.
     */
    public IotHubDeviceTelemetryEventData() {
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IotHubDeviceTelemetryEventData setBody(Object body) {
        super.setBody(body);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IotHubDeviceTelemetryEventData setProperties(Map<String, String> properties) {
        super.setProperties(properties);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IotHubDeviceTelemetryEventData setSystemProperties(Map<String, String> systemProperties) {
        super.setSystemProperties(systemProperties);
        return this;
    }

    /*
     * The content of the message from the device.
     */
    @Generated
    @JsonProperty(value = "body")
    private Object body;

    /*
     * Application properties are user-defined strings that can be added to the message. These fields are optional.
     */
    @Generated
    @JsonProperty(value = "properties")
    private Map<String, String> properties;

    /*
     * System properties help identify contents and source of the messages.
     */
    @Generated
    @JsonProperty(value = "systemProperties")
    private Map<String, String> systemProperties;

    /**
     * Get the body property: The content of the message from the device.
     *
     * @return the body value.
     */
    @Generated
    public Object getBody() {
        return this.body;
    }

    /**
     * Get the properties property: Application properties are user-defined strings that can be added to the message.
     * These fields are optional.
     *
     * @return the properties value.
     */
    @Generated
    public Map<String, String> getProperties() {
        return this.properties;
    }

    /**
     * Get the systemProperties property: System properties help identify contents and source of the messages.
     *
     * @return the systemProperties value.
     */
    @Generated
    public Map<String, String> getSystemProperties() {
        return this.systemProperties;
    }
}
