// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Event data for Microsoft.Devices.DeviceCreated event.
 */
@Fluent
public final class IotHubDeviceCreatedEventData {

    /**
     * Creates an instance of IotHubDeviceCreatedEventData class.
     */
    public IotHubDeviceCreatedEventData() {
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IotHubDeviceCreatedEventData setDeviceId(String deviceId) {
        super.setDeviceId(deviceId);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IotHubDeviceCreatedEventData setHubName(String hubName) {
        super.setHubName(hubName);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IotHubDeviceCreatedEventData setTwin(DeviceTwinInfo twin) {
        super.setTwin(twin);
        return this;
    }

    /*
     * The unique identifier of the device. This case-sensitive string can be up to 128 characters long, and supports
     * ASCII 7-bit alphanumeric characters plus the following special characters: - : . + % _ &#35; * ? ! ( ) , = @ ; $
     * '.
     */
    @Generated
    @JsonProperty(value = "deviceId")
    private String deviceId;

    /*
     * Name of the IoT Hub where the device was created or deleted.
     */
    @Generated
    @JsonProperty(value = "hubName")
    private String hubName;

    /*
     * Information about the device twin, which is the cloud representation of application device metadata.
     */
    @Generated
    @JsonProperty(value = "twin")
    private DeviceTwinInfo twin;

    /**
     * Get the deviceId property: The unique identifier of the device. This case-sensitive string can be up to 128
     * characters long, and supports ASCII 7-bit alphanumeric characters plus the following special characters: - : . +
     * % _ &amp;#35; * ? ! ( ) , = @ ; $ '.
     *
     * @return the deviceId value.
     */
    @Generated
    public String getDeviceId() {
        return this.deviceId;
    }

    /**
     * Get the hubName property: Name of the IoT Hub where the device was created or deleted.
     *
     * @return the hubName value.
     */
    @Generated
    public String getHubName() {
        return this.hubName;
    }

    /**
     * Get the twin property: Information about the device twin, which is the cloud representation of application
     * device metadata.
     *
     * @return the twin value.
     */
    @Generated
    public DeviceTwinInfo getTwin() {
        return this.twin;
    }
}
