// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Schema of the Data property of an EventGridEvent for a Microsoft.Maps.GeofenceEntered event.
 */
@Fluent
public final class MapsGeofenceEnteredEventData {

    /**
     * Creates an instance of MapsGeofenceEnteredEventData class.
     */
    public MapsGeofenceEnteredEventData() {
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MapsGeofenceEnteredEventData setExpiredGeofenceGeometryId(List<String> expiredGeofenceGeometryId) {
        super.setExpiredGeofenceGeometryId(expiredGeofenceGeometryId);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MapsGeofenceEnteredEventData setGeometries(List<MapsGeofenceGeometry> geometries) {
        super.setGeometries(geometries);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MapsGeofenceEnteredEventData
        setInvalidPeriodGeofenceGeometryId(List<String> invalidPeriodGeofenceGeometryId) {
        super.setInvalidPeriodGeofenceGeometryId(invalidPeriodGeofenceGeometryId);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MapsGeofenceEnteredEventData setIsEventPublished(Boolean isEventPublished) {
        super.setIsEventPublished(isEventPublished);
        return this;
    }

    /*
     * Lists of the geometry ID of the geofence which is expired relative to the user time in the request.
     */
    @Generated
    @JsonProperty(value = "expiredGeofenceGeometryId")
    private List<String> expiredGeofenceGeometryId;

    /*
     * Lists the fence geometries that either fully contain the coordinate position or have an overlap with the
     * searchBuffer around the fence.
     */
    @Generated
    @JsonProperty(value = "geometries")
    private List<MapsGeofenceGeometry> geometries;

    /*
     * Lists of the geometry ID of the geofence which is in invalid period relative to the user time in the request.
     */
    @Generated
    @JsonProperty(value = "invalidPeriodGeofenceGeometryId")
    private List<String> invalidPeriodGeofenceGeometryId;

    /*
     * True if at least one event is published to the Azure Maps event subscriber, false if no event is published to
     * the Azure Maps event subscriber.
     */
    @Generated
    @JsonProperty(value = "isEventPublished")
    private Boolean isEventPublished;

    /**
     * Get the expiredGeofenceGeometryId property: Lists of the geometry ID of the geofence which is expired relative
     * to the user time in the request.
     *
     * @return the expiredGeofenceGeometryId value.
     */
    @Generated
    public List<String> getExpiredGeofenceGeometryId() {
        return this.expiredGeofenceGeometryId;
    }

    /**
     * Get the geometries property: Lists the fence geometries that either fully contain the coordinate position or
     * have an overlap with the searchBuffer around the fence.
     *
     * @return the geometries value.
     */
    @Generated
    public List<MapsGeofenceGeometry> getGeometries() {
        return this.geometries;
    }

    /**
     * Get the invalidPeriodGeofenceGeometryId property: Lists of the geometry ID of the geofence which is in invalid
     * period relative to the user time in the request.
     *
     * @return the invalidPeriodGeofenceGeometryId value.
     */
    @Generated
    public List<String> getInvalidPeriodGeofenceGeometryId() {
        return this.invalidPeriodGeofenceGeometryId;
    }

    /**
     * Get the isEventPublished property: True if at least one event is published to the Azure Maps event subscriber,
     * false if no event is published to the Azure Maps event subscriber.
     *
     * @return the isEventPublished value.
     */
    @Generated
    public Boolean isEventPublished() {
        return this.isEventPublished;
    }
}
