// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Map;

/**
 * Job finished event data. Schema of the data property of an EventGridEvent for a Microsoft.Media.JobFinished event.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "#Microsoft.Media.JobFinished")
@JsonTypeName("MediaJobFinishedEventData")
@Fluent
public final class MediaJobFinishedEventData {

    /*
     * Gets the Job outputs.
     */
    @JsonProperty(value = "outputs")
    private List<MediaJobOutput> outputs;

    /**
     * Creates an instance of MediaJobFinishedEventData class.
     */
    public MediaJobFinishedEventData() {
    }

    /**
     * Get the outputs property: Gets the Job outputs.
     *
     * @return the outputs value.
     */
    public List<MediaJobOutput> getOutputs() {
        return this.outputs;
    }

    /**
     * Set the outputs property: Gets the Job outputs.
     *
     * @param outputs the outputs value to set.
     * @return the MediaJobFinishedEventData object itself.
     */
    public MediaJobFinishedEventData setOutputs(List<MediaJobOutput> outputs) {
        this.outputs = outputs;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MediaJobFinishedEventData setCorrelationData(Map<String, String> correlationData) {
        super.setCorrelationData(correlationData);
        return this;
    }

    /*
     * The previous state of the Job.
     */
    @Generated
    @JsonProperty(value = "previousState")
    private MediaJobState previousState;

    /*
     * The new state of the Job.
     */
    @Generated
    @JsonProperty(value = "state")
    private MediaJobState state;

    /*
     * Gets the Job correlation data.
     */
    @Generated
    @JsonProperty(value = "correlationData")
    private Map<String, String> correlationData;

    /**
     * Get the previousState property: The previous state of the Job.
     *
     * @return the previousState value.
     */
    @Generated
    public MediaJobState getPreviousState() {
        return this.previousState;
    }

    /**
     * Set the previousState property: The previous state of the Job.
     *
     * @param previousState the previousState value to set.
     * @return the MediaJobFinishedEventData object itself.
     */
    @Generated
    public MediaJobFinishedEventData setPreviousState(MediaJobState previousState) {
        this.previousState = previousState;
        return this;
    }

    /**
     * Get the state property: The new state of the Job.
     *
     * @return the state value.
     */
    @Generated
    public MediaJobState getState() {
        return this.state;
    }

    /**
     * Set the state property: The new state of the Job.
     *
     * @param state the state value to set.
     * @return the MediaJobFinishedEventData object itself.
     */
    @Generated
    public MediaJobFinishedEventData setState(MediaJobState state) {
        this.state = state;
        return this;
    }

    /**
     * Get the correlationData property: Gets the Job correlation data.
     *
     * @return the correlationData value.
     */
    @Generated
    public Map<String, String> getCorrelationData() {
        return this.correlationData;
    }
}
