// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;

/**
 * Job output canceled event data. Schema of the data property of an EventGridEvent for a
 * Microsoft.Media.JobOutputCanceled event.
 */
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "#Microsoft.Media.JobOutputCanceled")
@JsonTypeName("MediaJobOutputCanceledEventData")
@Fluent
public final class MediaJobOutputCanceledEventData {

    /**
     * Creates an instance of MediaJobOutputCanceledEventData class.
     */
    public MediaJobOutputCanceledEventData() {
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MediaJobOutputCanceledEventData setOutput(MediaJobOutput output) {
        super.setOutput(output);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MediaJobOutputCanceledEventData setJobCorrelationData(Map<String, String> jobCorrelationData) {
        super.setJobCorrelationData(jobCorrelationData);
        return this;
    }

    /*
     * The previous state of the Job.
     */
    @Generated
    @JsonProperty(value = "previousState")
    private MediaJobState previousState;

    /*
     * Gets the output.
     */
    @Generated
    @JsonProperty(value = "output")
    private MediaJobOutput output;

    /*
     * Gets the Job correlation data.
     */
    @Generated
    @JsonProperty(value = "jobCorrelationData")
    private Map<String, String> jobCorrelationData;

    /**
     * Get the previousState property: The previous state of the Job.
     *
     * @return the previousState value.
     */
    @Generated
    public MediaJobState getPreviousState() {
        return this.previousState;
    }

    /**
     * Set the previousState property: The previous state of the Job.
     *
     * @param previousState the previousState value to set.
     * @return the MediaJobOutputCanceledEventData object itself.
     */
    @Generated
    public MediaJobOutputCanceledEventData setPreviousState(MediaJobState previousState) {
        this.previousState = previousState;
        return this;
    }

    /**
     * Get the output property: Gets the output.
     *
     * @return the output value.
     */
    @Generated
    public MediaJobOutput getOutput() {
        return this.output;
    }

    /**
     * Get the jobCorrelationData property: Gets the Job correlation data.
     *
     * @return the jobCorrelationData value.
     */
    @Generated
    public Map<String, String> getJobCorrelationData() {
        return this.jobCorrelationData;
    }
}
