// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.messaging.eventgrid.systemevents;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The event data for a Job output asset.
 */
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "#Microsoft.Media.JobOutputAsset")
@JsonTypeName("MediaJobOutputAsset")
@Fluent
public final class MediaJobOutputAsset {

    /*
     * Gets the Job output asset name.
     */
    @JsonProperty(value = "assetName")
    private String assetName;

    /**
     * Creates an instance of MediaJobOutputAsset class.
     */
    public MediaJobOutputAsset() {
    }

    /**
     * Get the assetName property: Gets the Job output asset name.
     *
     * @return the assetName value.
     */
    public String getAssetName() {
        return this.assetName;
    }

    /**
     * Set the assetName property: Gets the Job output asset name.
     *
     * @param assetName the assetName value to set.
     * @return the MediaJobOutputAsset object itself.
     */
    public MediaJobOutputAsset setAssetName(String assetName) {
        this.assetName = assetName;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MediaJobOutputAsset setError(MediaJobError error) {
        super.setError(error);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MediaJobOutputAsset setLabel(String label) {
        super.setLabel(label);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MediaJobOutputAsset setProgress(long progress) {
        super.setProgress(progress);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MediaJobOutputAsset setState(MediaJobState state) {
        super.setState(state);
        return this;
    }

    /*
     * The discriminator for derived types.
     */
    @Generated
    @JsonProperty(value = "@odata.type")
    private String odataType;

    /*
     * Gets the Job output error.
     */
    @Generated
    @JsonProperty(value = "error")
    private MediaJobError error;

    /*
     * Gets the Job output label.
     */
    @Generated
    @JsonProperty(value = "label")
    private String label;

    /*
     * Gets the Job output progress.
     */
    @Generated
    @JsonProperty(value = "progress")
    private long progress;

    /*
     * Gets the Job output state.
     */
    @Generated
    @JsonProperty(value = "state")
    private MediaJobState state;

    /**
     * Get the odataType property: The discriminator for derived types.
     *
     * @return the odataType value.
     */
    @Generated
    public String getOdataType() {
        return this.odataType;
    }

    /**
     * Set the odataType property: The discriminator for derived types.
     *
     * @param odataType the odataType value to set.
     * @return the MediaJobOutputAsset object itself.
     */
    @Generated
    public MediaJobOutputAsset setOdataType(String odataType) {
        this.odataType = odataType;
        return this;
    }

    /**
     * Get the error property: Gets the Job output error.
     *
     * @return the error value.
     */
    @Generated
    public MediaJobError getError() {
        return this.error;
    }

    /**
     * Get the label property: Gets the Job output label.
     *
     * @return the label value.
     */
    @Generated
    public String getLabel() {
        return this.label;
    }

    /**
     * Get the progress property: Gets the Job output progress.
     *
     * @return the progress value.
     */
    @Generated
    public long getProgress() {
        return this.progress;
    }

    /**
     * Get the state property: Gets the Job output state.
     *
     * @return the state value.
     */
    @Generated
    public MediaJobState getState() {
        return this.state;
    }
}
